
export const capabilityCatalog = {
  tools: [
    'find_documents',
    'read_document',
    'save_document',
    'delete_document',
    'list_workspace_structure',
    'save_folder',
    'delete_folder',
    'save_category',
    'delete_category',
    'save_tag',
    'delete_tag',
    'set_document_tag',
    'create_snapshot',
    'restore_document_version',
    'explore_graph',
    'get_document_index_status',
    'refresh_document_index',
    'list_trash',
    'restore_trashed_document',
    'permanently_delete_document',
  ] as const,
  prompts: ['organize_workspace', 'research_workspace'] as const,
  resources: [
    'docsmint://guide/editor',
    'docsmint://guide/search',
    'docsmint://workspace/catalog',
  ] as const,
};
